#!/usr/bin/env python3
"""
AWS Service Cost Breakdown Generator
Parses an AWS Cost Explorer inventory JSON report (generated by get_cost_inventory.py)
and produces a comprehensive, tabular markdown report detailing per-service spend,
monthly trends, regional distribution, usage types, and purchase options.

Usage:
    python tools/generate_service_cost_breakdown.py -i output/853268358782/cost/cost-inventory-853268358782-20260902-083007.json
    python tools/generate_service_cost_breakdown.py -a 853268358782
    python tools/generate_service_cost_breakdown.py -a 853268358782 -o output/853268358782/cost/service-cost-report.md
"""

import argparse
import glob
import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def format_currency(val, decimals=2):
    """Format float into USD currency string."""
    if val is None:
        return "$0.00"
    if abs(val) < 0.005 and val != 0:
        return f"${val:.4f}"
    return f"${val:,.{decimals}f}"


def format_pct(val):
    """Format percentage float."""
    if val is None or val == 0:
        return "0.0%"
    if val < 0.05:
        return "<0.1%"
    return f"{val:.1f}%"


def slugify(text):
    """Create GitHub markdown anchor slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    return slug


def find_latest_cost_file(account_id, base_dir=None):
    """Find the most recent cost-inventory JSON for an account."""
    if base_dir is None:
        base_dir = Path(__file__).resolve().parent.parent / "output"
    pattern = os.path.join(base_dir, str(account_id), "cost", "cost-inventory-*.json")
    files = sorted(glob.glob(pattern))
    if not files:
        return None
    return files[-1]


def parse_cost_inventory(data, min_spend=0.0):
    """Parse raw cost JSON into structured per-service analytics."""
    account_id = data.get("name", "Unknown")
    profile = data.get("profile_used", "")
    period = data.get("period", {})
    ytd_total = data.get("ytd_total", 0.0)
    prior_month_total = data.get("prior_month_total", 0.0)
    mtd_total = data.get("mtd_total", 0.0)

    # Monthly periods in order
    monthly_items = data.get("ytd_by_service_monthly", [])
    distinct_months = sorted(list(set(item["period_start"] for item in monthly_items)))

    # Per-service monthly buckets: service -> month -> unblended_cost
    service_monthly = defaultdict(lambda: defaultdict(float))
    service_ytd_totals = defaultdict(float)

    for item in monthly_items:
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        month = item["period_start"]
        cost = float(item.get("unblended_cost", 0.0))
        service_monthly[service_name][month] += cost
        service_ytd_totals[service_name] += cost

    # Prior month by service
    service_prior_month = defaultdict(float)
    for item in data.get("prior_month_by_service", []):
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        service_prior_month[service_name] += float(item.get("unblended_cost", 0.0))

    # MTD by service
    service_mtd = defaultdict(float)
    for item in data.get("mtd_by_service", []):
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        service_mtd[service_name] += float(item.get("unblended_cost", 0.0))

    # Regional breakdown: service -> region -> cost
    service_regions = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_region", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            region = item["keys"][1]
            service_regions[s_name][region] += float(item.get("unblended_cost", 0.0))

    # Usage type breakdown: service -> usage_type -> cost
    service_usage_types = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_usage_type", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            ut = item["keys"][1]
            service_usage_types[s_name][ut] += float(item.get("unblended_cost", 0.0))

    # Purchase option breakdown: service -> option -> cost
    service_purchase_options = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_purchase_option", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            opt = item["keys"][1]
            service_purchase_options[s_name][opt] += float(item.get("unblended_cost", 0.0))

    # Linked account breakdown: service -> linked_account -> cost
    service_linked_accounts = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_linked_account", []):
        if len(item.get("keys", [])) >= 2:
            acct = item["keys"][0]
            s_name = item["keys"][1]
            service_linked_accounts[s_name][acct] += float(item.get("unblended_cost", 0.0))

    # All unique services sorted by YTD spend descending
    all_service_names = set(service_ytd_totals.keys()) | set(service_prior_month.keys()) | set(service_mtd.keys())
    sorted_services = sorted(
        [s for s in all_service_names if service_ytd_totals[s] >= min_spend or service_prior_month[s] > 0 or service_mtd[s] > 0],
        key=lambda s: service_ytd_totals[s],
        reverse=True,
    )

    return {
        "account_id": account_id,
        "profile": profile,
        "period": period,
        "ytd_total": ytd_total,
        "prior_month_total": prior_month_total,
        "mtd_total": mtd_total,
        "distinct_months": distinct_months,
        "sorted_services": sorted_services,
        "service_ytd_totals": service_ytd_totals,
        "service_monthly": service_monthly,
        "service_prior_month": service_prior_month,
        "service_mtd": service_mtd,
        "service_regions": service_regions,
        "service_usage_types": service_usage_types,
        "service_purchase_options": service_purchase_options,
        "service_linked_accounts": service_linked_accounts,
    }


def month_header(date_str):
    """Convert '2026-01-01' into 'Jan 2026'."""
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.strftime("%b %Y")
    except Exception:
        return date_str


def generate_markdown_report(parsed, top_n=10):
    """Generate presentation-ready tabular markdown document."""
    account_id = parsed["account_id"]
    period = parsed["period"]
    ytd_total = parsed["ytd_total"]
    prior_month_total = parsed["prior_month_total"]
    mtd_total = parsed["mtd_total"]
    months = parsed["distinct_months"]
    services = parsed["sorted_services"]

    lines = []
    lines.append(f"# AWS Service Cost Breakdown Report — Account `{account_id}`\n")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ")
    lines.append(f"**Account ID:** `{account_id}` | **Profile:** `{parsed['profile']}`  ")
    lines.append(
        f"**Analysis Period:** YTD `{period.get('ytd_start', '2026-01-01')}` to `{period.get('end', 'Present')}` "
        f"(Prior Month: `{period.get('prior_month_start', '')}` to `{period.get('prior_month_end', '')}`)\n"
    )
    lines.append("---\n")

    # High-level summary scorecard
    lines.append("## 📊 Executive Spend Summary\n")
    lines.append("```")
    lines.append("┌──────────────────────────────────────────────────────────────────────────────────────────────────┐")
    lines.append("│                                  ACCOUNT COST SUMMARY SCORECARD                                  │")
    lines.append("├──────────────────────────────┬──────────────────────────────┬────────────────────────────────────┤")
    lines.append(f"│       Total YTD Spend        │      Prior Month Spend       │          Current MTD Spend         │")
    lines.append(f"│       {format_currency(ytd_total):<22} │       {format_currency(prior_month_total):<22} │          {format_currency(mtd_total):<26}│")
    lines.append(f"│   (Services Tracked: {len(services):<6}) │   (Prior Month Total Spend)  │          (Month-to-Date Spend)     │")
    lines.append("└──────────────────────────────┴──────────────────────────────┴────────────────────────────────────┘")
    lines.append("```\n")

    # Master Ranking Table
    lines.append("### 🏆 Master Service Spend Ranking (All Services)\n")
    lines.append("| Rank | Service Name | YTD Spend | % of Total | Prior Month Spend | MTD Spend | MoM Trend |")
    lines.append("|---|---|---:|---:|---:|---:|---:|")

    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        pct_of_total = (ytd_spend / ytd_total * 100) if ytd_total > 0 else 0.0
        pm_spend = parsed["service_prior_month"].get(s_name, 0.0)
        mtd_spend = parsed["service_mtd"].get(s_name, 0.0)

        # Calculate MoM change (compare 2 most recent full months if available)
        if len(months) >= 2:
            prev_m = parsed["service_monthly"][s_name].get(months[-2], 0.0)
            prior_prev_m = parsed["service_monthly"][s_name].get(months[-3], 0.0) if len(months) >= 3 else 0.0
            if prior_prev_m > 0:
                diff = prev_m - prior_prev_m
                diff_pct = (diff / prior_prev_m) * 100
                trend_str = f"{'+' if diff >= 0 else ''}{diff_pct:.1f}%"
            else:
                trend_str = "—"
        else:
            trend_str = "—"

        anchor = slugify(f"{rank}. {s_name}")
        lines.append(
            f"| **{rank}** | [{s_name}](#{anchor}) | **{format_currency(ytd_spend)}** | {format_pct(pct_of_total)} | {format_currency(pm_spend)} | {format_currency(mtd_spend)} | {trend_str} |"
        )

    lines.append("\n---\n")

    # Table of Contents
    lines.append("## 📑 Table of Contents\n")
    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        anchor = slugify(f"{rank}. {s_name}")
        lines.append(f"- [{rank}. {s_name} ({format_currency(ytd_spend)})](#{anchor})")

    lines.append("\n---\n")

    # Per-Service Detail Sections
    lines.append("## 🔍 Detailed Per-Service Tabular Cost Breakdown\n")

    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        pm_spend = parsed["service_prior_month"].get(s_name, 0.0)
        mtd_spend = parsed["service_mtd"].get(s_name, 0.0)
        pct_of_total = (ytd_spend / ytd_total * 100) if ytd_total > 0 else 0.0
        avg_monthly = ytd_spend / max(1, len(months))

        lines.append(f"### {rank}. {s_name}\n")
        lines.append(f"- **Total YTD Spend:** `{format_currency(ytd_spend)}` ({format_pct(pct_of_total)} of account spend)")
        lines.append(f"- **Prior Month Spend:** `{format_currency(pm_spend)}` | **Current MTD Spend:** `{format_currency(mtd_spend)}`")
        lines.append(f"- **Average Monthly Spend:** `{format_currency(avg_monthly)}/mo`\n")

        # 1. Monthly Trend Table
        lines.append("#### 📅 Monthly Spend History")
        month_headers = [month_header(m) for m in months]
        lines.append("| " + " | ".join(month_headers) + " | **Total YTD** | **Monthly Avg** |")
        lines.append("|" + "|".join(["---:"] * (len(months) + 2)) + "|")

        row_vals = [format_currency(parsed["service_monthly"][s_name].get(m, 0.0)) for m in months]
        row_vals.append(f"**{format_currency(ytd_spend)}**")
        row_vals.append(f"**{format_currency(avg_monthly)}**")
        lines.append("| " + " | ".join(row_vals) + " |\n")

        # 2. Regional Breakdown
        regions = parsed["service_regions"].get(s_name, {})
        if regions:
            sorted_regions = sorted(regions.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### 🌐 Top Regions (Top {min(len(sorted_regions), top_n)})")
            lines.append("| Region | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for reg, r_cost in sorted_regions:
                r_pct = (r_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{reg}` | {format_currency(r_cost)} | {format_pct(r_pct)} |")
            lines.append("")

        # 3. Usage Type Breakdown
        usage_types = parsed["service_usage_types"].get(s_name, {})
        if usage_types:
            sorted_usage = sorted(usage_types.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### ⚙️ Top Usage Types (Top {min(len(sorted_usage), top_n)})")
            lines.append("| Usage Type | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for ut, u_cost in sorted_usage:
                u_pct = (u_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{ut}` | {format_currency(u_cost)} | {format_pct(u_pct)} |")
            lines.append("")

        # 4. Purchase Option Breakdown (if >1 option or meaningful)
        p_options = parsed["service_purchase_options"].get(s_name, {})
        if len(p_options) > 1 or (len(p_options) == 1 and list(p_options.keys())[0] != "On Demand Instances"):
            sorted_opts = sorted(p_options.items(), key=lambda x: x[1], reverse=True)
            lines.append("#### 🏷️ Purchase Options Breakdown")
            lines.append("| Purchase Option | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for opt, o_cost in sorted_opts:
                o_pct = (o_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| {opt} | {format_currency(o_cost)} | {format_pct(o_pct)} |")
            lines.append("")

        # 5. Linked Account Breakdown (if multiple accounts present)
        linked_accts = parsed["service_linked_accounts"].get(s_name, {})
        if len(linked_accts) > 1:
            sorted_accts = sorted(linked_accts.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### 🏢 Top Linked Accounts (Top {min(len(sorted_accts), top_n)})")
            lines.append("| Linked Account ID | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for acct, a_cost in sorted_accts:
                a_pct = (a_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{acct}` | {format_currency(a_cost)} | {format_pct(a_pct)} |")
            lines.append("")

        lines.append("---\n")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate per-service tabular markdown cost breakdown from cost inventory JSON")
    parser.add_argument("-i", "--input", default=None, help="Path to cost inventory JSON file")
    parser.add_argument("-a", "--account", default=None, help="AWS Account ID (finds latest cost inventory in output/<account>/cost/)")
    parser.add_argument("-o", "--output", default=None, help="Output markdown file path")
    parser.add_argument("--min-spend", type=float, default=0.0, help="Minimum YTD spend in USD to include in detail sections")
    parser.add_argument("--top-n", type=int, default=10, help="Max items in region/usage breakdown tables (default: 10)")
    args = parser.parse_args()

    input_file = args.input

    if not input_file and args.account:
        input_file = find_latest_cost_file(args.account)
        if not input_file:
            print(f"Error: No cost inventory JSON found for account {args.account} in output/{args.account}/cost/", file=sys.stderr)
            sys.exit(1)

    if not input_file:
        # Default fallback to 853268358782 if available
        input_file = find_latest_cost_file("853268358782")
        if not input_file:
            print("Error: Please provide --input <file.json> or --account <account_id>", file=sys.stderr)
            sys.exit(1)

    if not os.path.exists(input_file):
        print(f"Error: Input file not found: {input_file}", file=sys.stderr)
        sys.exit(1)

    print(f"📖 Loading cost inventory: {input_file}")
    with open(input_file, "r") as f:
        data = json.load(f)

    parsed = parse_cost_inventory(data, min_spend=args.min_spend)
    account_id = parsed["account_id"]
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    # Determine output path
    if args.output:
        output_path = args.output
    else:
        output_dir = Path(__file__).resolve().parent.parent / "output" / str(account_id) / "cost"
        os.makedirs(output_dir, exist_ok=True)
        output_path = str(output_dir / f"service-cost-breakdown-{account_id}-{timestamp}.md")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    print(f"⚙️  Generating markdown report for {len(parsed['sorted_services'])} services...")
    report_md = generate_markdown_report(parsed, top_n=args.top_n)

    with open(output_path, "w") as f:
        f.write(report_md)

    print(f"✅ Service cost report successfully generated!")
    print(f"📄 Output: {output_path}")
    print(f"📊 Total Services Analyzed: {len(parsed['sorted_services'])}")
    print(f"💰 Total YTD Spend: {format_currency(parsed['ytd_total'])}")


if __name__ == "__main__":
    main()
